name: CI
on: [push]
jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v1
    - uses: ruby/setup-ruby@v1
      env:
        ImageOS : macos11
      with:
        ruby-version: 2.6
        bundler-cache: true
        
    - name: Build and run tests
      run: |
        bundle exec fastlane build_app_for_testing
